### ISSUE TITLE
Crash app when read epub file 

### ISSUE THREAD

**Issue by umeshshende** [kaushikgodhani/vocsy_epub_viewer#54] opened 2024-02-06 17:48 UTC
It is working in debug apk but same not working in release apk 

```
     VocsyEpub.open(path,
          lastLocation: EpubLocator.fromJson({
            "bookId": bookid,
            "href": href,
            "created": created,
            "locations": {"cfi": location},
          }));
```

**Comment by YashVanani** [comment] 2024-06-11 17:46
I'm encountering an issue with my release APK. While it works fine in debug mode, it crashes on any Android version when running the release build.

**Comment by jalakamkiran** [comment] 2024-06-11 18:47
I found the issue the problem is its not able to parse the material color to hex code and send to the method channel. 
<img width="780" alt="image" src="https://github.com/kaushikgodhani/vocsy_epub_viewer/assets/39314292/7c3eaf92-3e77-42ae-a669-65f7f3fdbe7c">
The fix is simple we just have to replace the color with a static hex code for other devs to work.

Meaninwhile , @kaushikgodhani I can rise a PR if you are ok to fix this issue permanantly. Let me know on the same.

**Comment by rafaeuw** [comment] 2024-06-22 19:31
i have the same issue. @jalakamkiran. if you could, it would be nice if you could send the fix for this error in the issue.

**Comment by djoks** [comment] 2024-09-01 21:01
> i have the same issue. @jalakamkiran. if you could, it would be nice if you could send the fix for this error in the issue.

Check and let me know if this works: https://github.com/kaushikgodhani/vocsy_epub_viewer/pull/60

CC: @kaushikgodhani

**Comment by kaushikgodhani** [comment] 2024-09-02 09:26
SORRY FOR DELAY

PLEASE CHECK THIS NEW VERSION "vocsy_epub_viewer: ^3.0.0" AND GIVE YOUR REVIEW. THANK YOU @djoks

**Closed by kaushikgodhani** 2024-09-02 09:26 UTC
